language: "ja"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!.gitignore"
    - "!backend/app/db/alembic_*"
  path_instructions:
    - path: "**/*.py"
      instructions:
        "Review the Python code for conformity with Ruff linter and formatter.\
         Do not review the import path."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
  tools:
    # デフォルトでONだが効いてるか不明なのであえて明示化
    ruff:
      enabled: true
chat:
  auto_reply: true
